/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_romeno_QixTD */

#ifndef _Included_com_romeno_QixTD
#define _Included_com_romeno_QixTD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_romeno_QixTD
 * Method:    Start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_romeno_QixTD_Start
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
