#pragma once

#define POINT_SPLASH_GAME_TYPE	1
#define LINE_CASCADE_GAME_TYPE	1
#define PLATFORMER_GAME_TYPE	1
#define QIX_GAME_TYPE			1

#undef POINT_SPLASH_GAME_TYPE
#undef LINE_CASCADE_GAME_TYPE
#undef PLATFORMER_GAME_TYPE
#undef QIX_GAME_TYPE

//#define PLATFORMER_GAME_TYPE	1
#define QIX_GAME_TYPE			1
